== CM1

# Chapter 1

## Substainability

    - Efficiency
    - Take in consideration the economical aspect (affordable, have access to it)
    - Social (improving quality of life: water, food, health services, education)
    - Combination of several factors, Complexity
    - The solution feats to the Context


The world is complex, lot of different interactions
world economy, Global Society, Earth physical environment, Governance

Governance: 
    - Everything that can affect the decisions
    - Politicans makers (public)
    - Decision makers (private company)

Substainable Development is Embracing Complexity
Non linear phenomena
Emergent properties
Difficulties in perceiving them (Environment complexity, lot of systems interacting together)

**One size fits-all solution cannot exist**

Goals of the Substainable Development

    - Economic progress is widespread and extreme poverty is eliminiated
    - Social inclusion is guaranteed for all
    - The environment is protected for human-induced degradation
    - Good governance (by government and businessess) is achieved