== CM1

# Chapter 1

## Substainability

    - Efficiency
    - Take in consideration the economical aspect (affordable, have access to it)
    - Social (improving quality of life: water, food, health services, education)
    - Combination of several factors, Complexity
    - The solution feats to the Context


The world is complex, lot of different interactions
world economy, Global Society, Earth physical environment, Governance

Governance: 
    - Everything that can affect the decisions
    - Politicans makers (public)
    - Decision makers (private company)

Substainable Development is Embracing Complexity
Non linear phenomena
Emergent properties
Difficulties in perceiving them (Environment complexity, lot of systems interacting together)

**One size fits-all solution cannot exist**

Goals of the Substainable Development

    - Economic progress is widespread and extreme poverty is eliminiated
    - Social inclusion is guaranteed for all
    - The environment is protected for human-induced degradation
    - Good governance (by government and businessess) is achieved


## History of SD

After the Second World War 

**Marshall Plan** (1948)
    - Economic cooperation between country
    - Seems a good project at first
    - Works well on Europe; lets test it on other country
    - Works bad in other situation

### 70s 

Global Approach for local context doesn't work
Have to thinl for specific solution

First concern about global environment 

### 80s

**First Definition of the SD**

The idea of Substainable can be viewed as an oymoron:
    - Development is often associated to (unlimited) growth
    - Substainability refers to the (limited) carrying capacity of the Earth

**Can the growth continue forever ?**

### 90s

The concept of **Human development** became relevant

People are at the center of the development
Development for people and by people

Key features to be free as a citizens:
    - Good education
    - Good health
    - Economic Independance


## The New Millennium: The Age of SD

Define 8 priorities to achieve development

    - Hunger
    - Education
    - Rigths
    - ...

Mainly focus on Human Rigths
Maily appropriate for the situation of developped countries


**Official launch of the 17th SDGs**

Based on the 2030 agenda
Are including much larger topics
They are a Structure for all the different categories of countries
    - Leave no one behind
    - Put substainable development
    - Transform economy
    - Peace
    - Global partneurship
Goals are interconnected with each other


### SDG Overview

#### Global Progress Overview

- Limited Progress: About 35% pof targets show modest gins or remain stagnant
- Regression: Roughly 18% to 15% of the goals are experiencing a 'concerning reversal" of progress 
- ...


#### Major CHallegnes and Regressions

- Porverty and hunger: Over 800 millions preple still live in extreme Porverty
- Climate Change 2024 was recorder as the hottes year in history
- Financing Gap: Developing countries face a 54 trillion annual funding gap and a debt servicing burden of 1.4 trillion drainning ressources from development 
- Global Instability
