site:
  title: Notes de Cours
  start_page: tn09-doc::index.adoc
content:
  branches: HEAD
  sources:
  - url : .
    start_path: TN09
  - url: .
    start_path: SR03
  

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
