== Project Work


# System dynamic modelling

## A bit of history

System dynamic modelling born after the 2nd WW, Professor Jay W Forrester from MIT. He applied it first for General Electric, then Boston, then world dynamics, then the environmental limit of growth: the beginning of sustainable development.  
Then John D. Sterman took Forrester’s work and contributed to conceptualize System Dynamics Theory, characterized by : 

* Non linear phenomena  
* Feedback chain: cause and effects links are not linear  
* Delay in Time: (most innovative part) 

## Use 

Every problem can be tackled using these method if it includes the 3 key factors (otherwise System Dynamics is useless)  
The effect of the feedback chain can be either positive or negative.

Problem **Boundaries** definition :   
We need to choose what to study and what to cut out, also we have to choose a time boundary (thus primary education would be irrelevant because the effects would be seen in the next generation, crossing the time boundary)

# Project Work 

Ouput : report (template to use), presentation (10min \+ Q\&A 5-10 min)  
Objective : designing policy for impact on Water, Energy, Climate

To support SDGs:

* SDG 6 Clean water  
* SDG 7 affordable and clean energy  
* SDG 13 Climate change

Why Ethiopia and Egypt

Last year, Ethiopia creates hydro-electric plants that is regulating the flow of the Nile

Egypt depends on the Nile for nearly all its freshwater- 60% from the blue Nile

## Modelling Process

. Problem articulation and Problem Boundaries Definition  
     
Define the boundaries, indicators of our model  

* Water Scarcity  
* Civil use of water  
* Agricultural needs  
* Energy supply (Ethiopia, check for egypt)  
* all the needs of Ethiopia will influence the Dam filling  
   
. Conceptualization of the Dynamic Hypothesis by means of Casual Loop Diagrams  
. Formulation of a Simulation Model with mathematical equations  
. Testing the Model Structure and Behaviour  
. Policy Evaluation

====

Homework : Identify the closure of the loop \= how Egypt’s behaviour can influence Ethiopia (the other cause-effect relation is obvious with Ethiopia's dams)

Describe the selected country and compare it to Africa and other geographical regions using country indicators (e.g. : GDP, HDI, EISD, …) and SDGs specific indicators 

Identify the relevant problems that affects the selected area in terms of SDGs 6,7 and 13, identify the current policy for the selected country, and create a general overview of the country

====

# Model Explanation

## Choose of a loop

### Reinforcing/Balancing loop

We beging with a side, we increase it and we look how the link will act, once we get back to the origin point we observe. If we finish by increasing the starting point it means it is as **Reinforcement loop**

We begin with increase and finish by decreasing, it is a **Balancing loop**

## Variable

### Exogenous Variables

Variable that we assume with a value 
Called as auxiliary variable 

* Reproductive lifetime
* Urban population share

You can choose to change this variables, if it makes sense
Looks like a constant

### Endogenous Variables

Called as parameters, needs to be set for generating the model
Something that is calculated within the model 

* Total Fertility rate


Better to leave it as it is. If you are confident and understand how they are defined, you can change it but you have to explain the reason and everything

### Flow Variable


Combination of stock and auxiliary 
The peculiarity of this variable is the unit of times when it happens.

* Birth rate 

### Stock Variable 

Integral over time of certain inflow minus certain integral over time of an outflow
Can be represented as a bathtub

* Population 0 to 14

### Variabes to act on it 

You can change some variables, depending of the policy of the country

* Desired energy mix by sector
** The column need to add to 1

## Policy Implementation 

### Energy

#### Egypt 

Use a lot of fossile Fuels

Only 12% of Renewable energy

* And 3% of wind
** But Egypt has a huge wind power 

    Capacity Factor = 0.35 Gwh/h 

    +13.54GW*0.35GWh/h * 8760h/y = + 41513 Gwh/y 

If we increase the wind energy, Total generation still needs to match total demand
So we can substract to other sectors 

=> Need to decrease Natural gase by 12.15 GW 


# Cooperative Scenarios

So far 

* We only focused on our own country's goal 
* Policies were designed to optimize national outcomes (food, water, energy)
* But you may have ignored transboundary impacts

## How to build a Cooperative Scenario 

. Identify the shared element
** Focus on a transboundary ressource (Blue Nile water, electricity export, food trade)
. Define a cooperation mechanism
. Balance incentives and responsabilities
** Ensure that both countries gain 
. Asses systemic impact 
** Simulate the impacts on both countries in the model 